[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

[lib]
name = "kvstore"
path = "src/kvstore/mod.rs"

[[bin]]
name = "kvstore"
path = "src/main.rs"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.7", features = ["derive"] }
crc = "3.2.1"
